# Generated by Django 2.2.5 on 2019-11-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_auto_20191111_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default='No Category', on_delete=django.db.models.deletion.CASCADE, to='web_app.Category'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='recipe',
            field=models.ForeignKey(blank=True, default='No Recipe', on_delete=django.db.models.deletion.CASCADE, to='web_app.Recipe'),
        ),
    ]
